name: Deploy Client to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'client/**'
      - '.github/workflows/deploy-client.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
        working-directory: ./client
      - run: npm run build
        working-directory: ./client
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./client/dist
      - uses: actions/deploy-pages@v4
