name: Yad2 Scraper

on:
  schedule:
    - cron: '13,43 5-18 * * *'
  workflow_dispatch:
    

jobs:
  scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packages
        run: |
          pip install -r requirements.txt
          python -m camoufox fetch

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"

      - name: Set Environment Variables
        run: |
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV
          echo "FB_C_USER=${{ secrets.FB_C_USER }}" >> $GITHUB_ENV
          echo "FB_XS=${{ secrets.FB_XS }}" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> $GITHUB_ENV

      - name: Clean caches
        run: python clean_caches.py

      - name: Run Yad2
        if: always()
        run: python yad2_scraper.py

      - name: Run Madlan
        if: always()
        run: python madlan_scraper.py

      - name: Run Facebook
        if: always()
        run: python facebook_scraper.py

      - name: Push new json data if needed
        if: always()
        run: |
          if [ -f ./push_me ]; then
            echo Pushing to Github...
            git add data
            DATE=$(date +"%F, %H:%M:%S")
            git commit -m "updated data - $DATE"
            git push
          fi


